services:
  app:
    image: ghcr.io/pikkerdev/time-tracker
    environment:
      - ENV=prod
      - NUM_WORKERS
      - SESSION_SECRET
      - DB_USER
      - DB_PASS
      - DB_APP_PASS
      - INITIAL_ADMINS
      - OWN_DOMAIN
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
    networks:
      - proxy
      - default
    labels:
      - caddy=time.pikker.dev
      - caddy.reverse_proxy={{upstreams 8080}}
      - caddy.reverse_proxy.lb_retries=10
      - caddy.reverse_proxy.lb_try_interval=500ms
      - caddy.log=
      - caddy.log.output=file /data/tms-access.log
      - caddy.log.format=json

networks:
  proxy:
    external: true
