--substitute id=id bigint primary key
--substitute createdBy=createdBy bigint default get_app_user()

--include app_user.sql
--include change_history.sql
--include users.sql
--include customers.sql
--include projects.sql
--include project_member.sql
--include time_entry.sql
--include invoices.sql
